version: '3.8'

services:
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cto-orchestrator
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./orchestrator:/app/orchestrator
      - ./configs:/app/configs
      - ./workspace:/workspace
    environment:
      - DOCKER_SOCKET=/var/run/docker.sock
      - API_HOST=0.0.0.0
      - API_PORT=8000
    networks:
      - cto_network
    restart: unless-stopped

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: cto-dashboard
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - orchestrator
    networks:
      - cto_network

networks:
  cto_network:
    driver: bridge